/* Generated by re2c 1.0.3 */
//-----------------------------------------------------------------------------
// z80asm assembler
// preprocessor
// Copyright (C) Paulo Custodio, 2011-20180
// License: http://www.perlfoundation.org/artistic_license_2_0
//-----------------------------------------------------------------------------
#include "ccdefs.h"

#define YYMAXFILL 8





void Preproc::init_scan(const std::string& text_)
{
    text = text_;
    text.reserve(text.length() + YYMAXFILL);
    p = text.c_str();
}

int Preproc::is_keyword()
{
    const char* YYMARKER;
    auto p0 = p;

    {
        char yych;
        yych = *p;

        switch (yych) {
        case '\t':
        case '\n':
        case '\v':
        case '\f':
        case '\r':
        case ' ':
            goto yy4;

        case 'I':
        case 'i':
            goto yy5;

        default:
            goto yy2;
        }

yy2:
        ++p;
yy3: {
            p = p0;
            return NONE;
        }
yy4:
        yych = *(YYMARKER = ++p);

        switch (yych) {
        case '\t':
        case '\n':
        case '\v':
        case '\f':
        case '\r':
        case ' ':
            goto yy6;

        case 'I':
        case 'i':
            goto yy9;

        default:
            goto yy3;
        }

yy5:
        yych = *(YYMARKER = ++p);

        switch (yych) {
        case 'N':
        case 'n':
            goto yy10;

        default:
            goto yy3;
        }

yy6:
        yych = *++p;

        switch (yych) {
        case '\t':
        case '\n':
        case '\v':
        case '\f':
        case '\r':
        case ' ':
            goto yy6;

        case 'I':
        case 'i':
            goto yy9;

        default:
            goto yy8;
        }

yy8:
        p = YYMARKER;
        goto yy3;
yy9:
        yych = *++p;

        switch (yych) {
        case 'N':
        case 'n':
            goto yy10;

        default:
            goto yy8;
        }

yy10:
        yych = *++p;

        switch (yych) {
        case 'C':
        case 'c':
            goto yy11;

        default:
            goto yy8;
        }

yy11:
        yych = *++p;

        switch (yych) {
        case 'L':
        case 'l':
            goto yy12;

        default:
            goto yy8;
        }

yy12:
        yych = *++p;

        switch (yych) {
        case 'U':
        case 'u':
            goto yy13;

        default:
            goto yy8;
        }

yy13:
        yych = *++p;

        switch (yych) {
        case 'D':
        case 'd':
            goto yy14;

        default:
            goto yy8;
        }

yy14:
        yych = *++p;

        switch (yych) {
        case 'E':
        case 'e':
            goto yy15;

        default:
            goto yy8;
        }

yy15:
        ++p;
        {
            return INCLUDE;
        }
    }

}

std::string Preproc::is_label()
{
    const char* YYMARKER, *p1, *p2, *yyt1, *yyt2;
    auto p0 = p;

    {
        char yych;
        yych = *p;

        switch (yych) {
        case '\t':
        case '\n':
        case '\v':
        case '\f':
        case '\r':
        case ' ':
            goto yy21;

        case '.':
            goto yy22;

        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'G':
        case 'H':
        case 'I':
        case 'J':
        case 'K':
        case 'L':
        case 'M':
        case 'N':
        case 'O':
        case 'P':
        case 'Q':
        case 'R':
        case 'S':
        case 'T':
        case 'U':
        case 'V':
        case 'W':
        case 'X':
        case 'Y':
        case 'Z':
        case '_':
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f':
        case 'g':
        case 'h':
        case 'i':
        case 'j':
        case 'k':
        case 'l':
        case 'm':
        case 'n':
        case 'o':
        case 'p':
        case 'q':
        case 'r':
        case 's':
        case 't':
        case 'u':
        case 'v':
        case 'w':
        case 'x':
        case 'y':
        case 'z':
            yyt1 = p;
            goto yy23;

        default:
            goto yy19;
        }

yy19:
        ++p;
yy20: {
            p = p0;
            return std::string();
        }
yy21:
        yych = *(YYMARKER = ++p);

        switch (yych) {
        case '\t':
        case '\n':
        case '\v':
        case '\f':
        case '\r':
        case ' ':
            goto yy24;

        case '.':
            goto yy27;

        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'G':
        case 'H':
        case 'I':
        case 'J':
        case 'K':
        case 'L':
        case 'M':
        case 'N':
        case 'O':
        case 'P':
        case 'Q':
        case 'R':
        case 'S':
        case 'T':
        case 'U':
        case 'V':
        case 'W':
        case 'X':
        case 'Y':
        case 'Z':
        case '_':
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f':
        case 'g':
        case 'h':
        case 'i':
        case 'j':
        case 'k':
        case 'l':
        case 'm':
        case 'n':
        case 'o':
        case 'p':
        case 'q':
        case 'r':
        case 's':
        case 't':
        case 'u':
        case 'v':
        case 'w':
        case 'x':
        case 'y':
        case 'z':
            yyt1 = p;
            goto yy28;

        default:
            goto yy20;
        }

yy22:
        yych = *++p;

        switch (yych) {
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'G':
        case 'H':
        case 'I':
        case 'J':
        case 'K':
        case 'L':
        case 'M':
        case 'N':
        case 'O':
        case 'P':
        case 'Q':
        case 'R':
        case 'S':
        case 'T':
        case 'U':
        case 'V':
        case 'W':
        case 'X':
        case 'Y':
        case 'Z':
        case '_':
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f':
        case 'g':
        case 'h':
        case 'i':
        case 'j':
        case 'k':
        case 'l':
        case 'm':
        case 'n':
        case 'o':
        case 'p':
        case 'q':
        case 'r':
        case 's':
        case 't':
        case 'u':
        case 'v':
        case 'w':
        case 'x':
        case 'y':
        case 'z':
            yyt1 = p;
            goto yy30;

        default:
            goto yy20;
        }

yy23:
        yych = *(YYMARKER = ++p);

        switch (yych) {
        case '\t':
        case '\n':
        case '\v':
        case '\f':
        case '\r':
        case ' ':
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        case ':':
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'G':
        case 'H':
        case 'I':
        case 'J':
        case 'K':
        case 'L':
        case 'M':
        case 'N':
        case 'O':
        case 'P':
        case 'Q':
        case 'R':
        case 'S':
        case 'T':
        case 'U':
        case 'V':
        case 'W':
        case 'X':
        case 'Y':
        case 'Z':
        case '_':
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f':
        case 'g':
        case 'h':
        case 'i':
        case 'j':
        case 'k':
        case 'l':
        case 'm':
        case 'n':
        case 'o':
        case 'p':
        case 'q':
        case 'r':
        case 's':
        case 't':
        case 'u':
        case 'v':
        case 'w':
        case 'x':
        case 'y':
        case 'z':
            goto yy37;

        default:
            goto yy20;
        }

yy24:
        yych = *++p;

        switch (yych) {
        case '\t':
        case '\n':
        case '\v':
        case '\f':
        case '\r':
        case ' ':
            goto yy24;

        case '.':
            goto yy27;

        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'G':
        case 'H':
        case 'I':
        case 'J':
        case 'K':
        case 'L':
        case 'M':
        case 'N':
        case 'O':
        case 'P':
        case 'Q':
        case 'R':
        case 'S':
        case 'T':
        case 'U':
        case 'V':
        case 'W':
        case 'X':
        case 'Y':
        case 'Z':
        case '_':
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f':
        case 'g':
        case 'h':
        case 'i':
        case 'j':
        case 'k':
        case 'l':
        case 'm':
        case 'n':
        case 'o':
        case 'p':
        case 'q':
        case 'r':
        case 's':
        case 't':
        case 'u':
        case 'v':
        case 'w':
        case 'x':
        case 'y':
        case 'z':
            yyt1 = p;
            goto yy28;

        default:
            goto yy26;
        }

yy26:
        p = YYMARKER;
        goto yy20;
yy27:
        yych = *++p;

        switch (yych) {
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'G':
        case 'H':
        case 'I':
        case 'J':
        case 'K':
        case 'L':
        case 'M':
        case 'N':
        case 'O':
        case 'P':
        case 'Q':
        case 'R':
        case 'S':
        case 'T':
        case 'U':
        case 'V':
        case 'W':
        case 'X':
        case 'Y':
        case 'Z':
        case '_':
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f':
        case 'g':
        case 'h':
        case 'i':
        case 'j':
        case 'k':
        case 'l':
        case 'm':
        case 'n':
        case 'o':
        case 'p':
        case 'q':
        case 'r':
        case 's':
        case 't':
        case 'u':
        case 'v':
        case 'w':
        case 'x':
        case 'y':
        case 'z':
            yyt1 = p;
            goto yy30;

        default:
            goto yy26;
        }

yy28:
        yych = *++p;

        switch (yych) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'G':
        case 'H':
        case 'I':
        case 'J':
        case 'K':
        case 'L':
        case 'M':
        case 'N':
        case 'O':
        case 'P':
        case 'Q':
        case 'R':
        case 'S':
        case 'T':
        case 'U':
        case 'V':
        case 'W':
        case 'X':
        case 'Y':
        case 'Z':
        case '_':
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f':
        case 'g':
        case 'h':
        case 'i':
        case 'j':
        case 'k':
        case 'l':
        case 'm':
        case 'n':
        case 'o':
        case 'p':
        case 'q':
        case 'r':
        case 's':
        case 't':
        case 'u':
        case 'v':
        case 'w':
        case 'x':
        case 'y':
        case 'z':
            goto yy28;

        case ':':
            goto yy38;

        default:
            goto yy26;
        }

yy30:
        yych = *++p;

        switch (yych) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'G':
        case 'H':
        case 'I':
        case 'J':
        case 'K':
        case 'L':
        case 'M':
        case 'N':
        case 'O':
        case 'P':
        case 'Q':
        case 'R':
        case 'S':
        case 'T':
        case 'U':
        case 'V':
        case 'W':
        case 'X':
        case 'Y':
        case 'Z':
        case '_':
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f':
        case 'g':
        case 'h':
        case 'i':
        case 'j':
        case 'k':
        case 'l':
        case 'm':
        case 'n':
        case 'o':
        case 'p':
        case 'q':
        case 'r':
        case 's':
        case 't':
        case 'u':
        case 'v':
        case 'w':
        case 'x':
        case 'y':
        case 'z':
            goto yy30;

        default:
            goto yy32;
        }

yy32:
        p1 = yyt1;
        p2 = p;
        {
            return std::string(p1, p2);
        }
yy33:
        yych = *++p;

        switch (yych) {
        case '\t':
        case '\n':
        case '\v':
        case '\f':
        case '\r':
        case ' ':
            goto yy33;

        default:
            goto yy35;
        }

yy35:
        p1 = yyt1;
        p2 = yyt2;
        {

            if (is_keyword() != NONE) {     // column-1 name followed by keyword

                p = p2;                     // go back to before keyword

                return std::string(p1, p2);

            }

            else {

                p = p0;
                return std::string();

            }

        }
yy36:
        yych = *++p;
yy37:

        switch (yych) {
        case '\t':
        case '\n':
        case '\v':
        case '\f':
        case '\r':
        case ' ':
            yyt2 = p;
            goto yy33;

        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'G':
        case 'H':
        case 'I':
        case 'J':
        case 'K':
        case 'L':
        case 'M':
        case 'N':
        case 'O':
        case 'P':
        case 'Q':
        case 'R':
        case 'S':
        case 'T':
        case 'U':
        case 'V':
        case 'W':
        case 'X':
        case 'Y':
        case 'Z':
        case '_':
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f':
        case 'g':
        case 'h':
        case 'i':
        case 'j':
        case 'k':
        case 'l':
        case 'm':
        case 'n':
        case 'o':
        case 'p':
        case 'q':
        case 'r':
        case 's':
        case 't':
        case 'u':
        case 'v':
        case 'w':
        case 'x':
        case 'y':
        case 'z':
            goto yy36;

        case ':':
            goto yy38;

        default:
            goto yy26;
        }

yy38:
        ++p;
        p1 = yyt1;
        p2 = p - 1;
        {
            return std::string(p1, p2);
        }
    }

}

std::string Preproc::get_include_filename()
{
    const char* YYMARKER, *p1, *p2, *yyt1, *yyt2;
    auto p0 = p;


    {
        char yych;
        yych = *p;

        switch (yych) {
        case '\t':
        case '\n':
        case '\v':
        case '\f':
        case '\r':
        case ' ':
            goto yy44;

        case '"':
            goto yy45;

        case '\'':
            goto yy46;

        case '<':
            goto yy47;

        default:
            goto yy42;
        }

yy42:
        ++p;
yy43: {
            p = p0;
            err.e_syntax(*this);
            return std::string();
        }
yy44:
        yych = *(YYMARKER = ++p);

        switch (yych) {
        case 0x00:
        case ';':
            goto yy43;

        default:
            goto yy52;
        }

yy45:
        yych = *++p;

        switch (yych) {
        case 0x00:
        case '\t':
        case '\n':
        case '\v':
        case '\f':
        case '\r':
        case '"':
        case ';':
            goto yy43;

        default:
            yyt2 = p;
            goto yy57;
        }

yy46:
        yych = *++p;

        switch (yych) {
        case 0x00:
        case '\t':
        case '\n':
        case '\v':
        case '\f':
        case '\r':
        case '\'':
        case ';':
            goto yy43;

        default:
            yyt2 = p;
            goto yy60;
        }

yy47:
        yych = *++p;

        switch (yych) {
        case 0x00:
        case '\t':
        case '\n':
        case '\v':
        case '\f':
        case '\r':
        case ';':
        case '>':
            goto yy43;

        default:
            yyt2 = p;
            goto yy63;
        }

yy48:
        yych = *++p;

        switch (yych) {
        case 0x00:
        case '\t':
        case '\n':
        case '\v':
        case '\f':
        case '\r':
        case ' ':
        case ';':
            goto yy50;

        default:
            goto yy48;
        }

yy50:
        p1 = yyt1;
        p2 = p;
        {
            return std::string(p1, p2);
        }
yy51:
        yych = *++p;
yy52:

        switch (yych) {
        case 0x00:
        case ';':
            goto yy53;

        case '\t':
        case '\n':
        case '\v':
        case '\f':
        case '\r':
        case ' ':
            goto yy51;

        case '"':
            yyt1 = p;
            goto yy54;

        case '\'':
            yyt1 = p;
            goto yy55;

        case '<':
            yyt1 = p;
            goto yy56;

        default:
            yyt1 = p;
            goto yy48;
        }

yy53:
        p = YYMARKER;
        goto yy43;
yy54:
        yych = *++p;

        switch (yych) {
        case 0x00:
        case '\t':
        case '\n':
        case '\v':
        case '\f':
        case '\r':
        case ';':
            goto yy50;

        case ' ':
            yyt2 = p;
            goto yy57;

        case '"':
            goto yy48;

        default:
            yyt2 = p;
            goto yy66;
        }

yy55:
        yych = *++p;

        switch (yych) {
        case 0x00:
        case '\t':
        case '\n':
        case '\v':
        case '\f':
        case '\r':
        case ';':
            goto yy50;

        case ' ':
            yyt2 = p;
            goto yy60;

        case '\'':
            goto yy48;

        default:
            yyt2 = p;
            goto yy68;
        }

yy56:
        yych = *++p;

        switch (yych) {
        case 0x00:
        case '\t':
        case '\n':
        case '\v':
        case '\f':
        case '\r':
        case ';':
            goto yy50;

        case ' ':
            yyt2 = p;
            goto yy63;

        case '>':
            goto yy48;

        default:
            yyt2 = p;
            goto yy70;
        }

yy57:
        yych = *++p;

        switch (yych) {
        case 0x00:
        case '\t':
        case '\n':
        case '\v':
        case '\f':
        case '\r':
        case ';':
            goto yy59;

        case '"':
            goto yy72;

        default:
            goto yy57;
        }

yy59: {
            err.e_syntax(*this);
            return std::string();
        }
yy60:
        yych = *++p;

        switch (yych) {
        case 0x00:
        case '\t':
        case '\n':
        case '\v':
        case '\f':
        case '\r':
        case ';':
            goto yy62;

        case '\'':
            goto yy74;

        default:
            goto yy60;
        }

yy62: {
            err.e_syntax(*this);
            return std::string();
        }
yy63:
        yych = *++p;

        switch (yych) {
        case 0x00:
        case '\t':
        case '\n':
        case '\v':
        case '\f':
        case '\r':
        case ';':
            goto yy65;

        case '>':
            goto yy76;

        default:
            goto yy63;
        }

yy65: {
            err.e_syntax(*this);
            return std::string();
        }
yy66:
        yych = *++p;

        switch (yych) {
        case 0x00:
        case '\t':
        case '\n':
        case '\v':
        case '\f':
        case '\r':
        case ';':
            goto yy59;

        case ' ':
            goto yy57;

        case '"':
            goto yy78;

        default:
            goto yy66;
        }

yy68:
        yych = *++p;

        switch (yych) {
        case 0x00:
        case '\t':
        case '\n':
        case '\v':
        case '\f':
        case '\r':
        case ';':
            goto yy62;

        case ' ':
            goto yy60;

        case '\'':
            goto yy79;

        default:
            goto yy68;
        }

yy70:
        yych = *++p;

        switch (yych) {
        case 0x00:
        case '\t':
        case '\n':
        case '\v':
        case '\f':
        case '\r':
        case ';':
            goto yy65;

        case ' ':
            goto yy63;

        case '>':
            goto yy80;

        default:
            goto yy70;
        }

yy72:
        ++p;
yy73:
        p1 = yyt2;
        p2 = p - 1;
        {
            return std::string(p1, p2);
        }
yy74:
        ++p;
yy75:
        p1 = yyt2;
        p2 = p - 1;
        {
            return std::string(p1, p2);
        }
yy76:
        ++p;
yy77:
        p1 = yyt2;
        p2 = p - 1;
        {
            return std::string(p1, p2);
        }
yy78:
        yych = *++p;

        switch (yych) {
        case 0x00:
        case '\t':
        case '\n':
        case '\v':
        case '\f':
        case '\r':
        case ' ':
        case ';':
            goto yy73;

        default:
            goto yy48;
        }

yy79:
        yych = *++p;

        switch (yych) {
        case 0x00:
        case '\t':
        case '\n':
        case '\v':
        case '\f':
        case '\r':
        case ' ':
        case ';':
            goto yy75;

        default:
            goto yy48;
        }

yy80:
        yych = *++p;

        switch (yych) {
        case 0x00:
        case '\t':
        case '\n':
        case '\v':
        case '\f':
        case '\r':
        case ' ':
        case ';':
            goto yy77;

        default:
            goto yy48;
        }
    }

}
